# .graphqlrc.yml
schema: "https://2dw9tmtv-3035.use2.devtunnels.ms/graphql"
documents: "graphql/**/*.graphql"
generates:
  graphql/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      withHooks: true
